version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/backend/
    ports:
      - 8000:8000
    environment:
      - DB_NAME=dev
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=dev_password
      - DB_USER=dev_user
    # env_file:
    #   - ./.env.dev
    # stdin_open: true
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev
    ports:
      - 5432:5432
volumes:
  postgres_data:
