version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: .
 #     dockerfile: Dockerfile
    command: ["/app/startup_script.sh"]
    #volumes:
#      - ./:/usr/src/backend/
    #  - ./:app/
    ports:
      - 8000:8000
    env_file: 
      - .env
    # env_file:
    #   - ./.env.dev
    # stdin_open: true
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: 'defaultdb'
      POSTGRES_USER: 'cmpe'
      POSTGRES_PASSWORD: 'cmpe'
    ports:
      - 5432:5432
volumes:
  postgres_data:
