# Generated by Django 3.2.4 on 2021-06-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ETFSector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='industry',
            field=models.CharField(max_length=50),
        ),
    ]
