export const LOGIN_URL = 'WE ARE WAITING FOR BACKEND';
export const SIGNUP_URL = 'WE ARE WAITING FOR BACKEND';
export const EDIT_USER_URL = 'WE ARE WAITING FOR BACKEND';
export const REFRESH_TOKEN_URL = 'WE ARE WAITING FOR BACKEND';
