# This is a basic workflow to help you get started with Actions
# The required steps followed from the page : https://medium.com/trackstack/deploying-a-react-app-to-aws-s3-with-github-actions-b1cb9ba75c95
name: Production Build

# Controls when the workflow will run
on:
  push:
    branches: [ frontend/develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn Install
        run: |
          cd source/frontend
          yarn install
      - name: Production Build
        run: |
          cd source/frontend
          CI= yarn build
      - name: Unit Tests
        run: |
          CI=true yarn test
          
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: bounswe11.com
          AWS_ACCESS_KEY_ID: AKIAXZ2EBCZWG57YHQNN
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: us-east-2
          SOURCE_DIR: "source/frontend/build"


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      
